# Generated by Django 4.2.4 on 2023-09-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='genre_movies', to='movie_app.genre'),
        ),
    ]
